version: '3'
services:

  rcvlabeltoollitebackend:
    build:
      context: ./rcv.labeltool.lite.backend
      dockerfile: Dockerfile
    image: rcv.labeltool.lite.backend:latest
    restart: always
    networks:
      - rcv-lite-net
    ports:
      - "19001:80"
    volumes:
      - "/c//rcv-labeltool-lite:/training-data"
      
  rcvlabeltoollite:
    build:
      context: ./rcv.labeltool.lite
      dockerfile: Dockerfile
    image: rcv.labeltool.lite:latest
    restart: always
    networks:
      - rcv-lite-net
    ports:
      - "80:80"
    depends_on:
      - rcvlabeltoollitebackend    
 
networks:
  rcv-lite-net: