version: "3"
services:
  labeltool-lite-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
          http_proxy: ""
          https_proxy: ""
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
    image: labeltool.lite.backend:latest
    restart: unless-stopped
    networks:
      - labeltool-lite-net
    ports:
      - "8000:80"
    volumes:
      - "./data/training-data:/training-data"

  labeltool-lite-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
          http_proxy: ""
          https_proxy: ""
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
    image: labeltool.lite.frontend:latest
    restart: unless-stopped
    networks:
      - labeltool-lite-net
    ports:
      - "8081:80"
    depends_on:
      - labeltool-lite-backend

  labeltool-lite-inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
      args:
          http_proxy: ""
          https_proxy: ""
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
    image: labeltool.lite.inferance:latest
    networks:
      - labeltool-lite-net
    volumes:
      - "./data/inference-data/models:/models"
      - "./data/inference-data/models_hash:/models_hash"
      
networks:
  labeltool-lite-net:
